# Generated by Django 5.1.1 on 2024-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_event_meet_link_alter_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.CharField(default=None, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_refresh_token',
            field=models.CharField(default=None, null=True, blank=True),
        ),
    ]
